name: Apply heal8s Remediation

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  apply-remediation:
    # Only run on merged PRs with heal8s label
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'heal8s')
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract environment from PR labels
        id: extract-env
        run: |
          # Extract environment from labels (dev, staging, prod)
          LABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'
          if echo "$LABELS" | grep -q "prod"; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif echo "$LABELS" | grep -q "staging"; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'
      
      - name: Configure kubectl for environment
        env:
          KUBECONFIG_CONTENT: ${{ secrets[format('KUBECONFIG_{0}', steps.extract-env.outputs.environment)] }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          
          # Verify connection
          kubectl cluster-info
          kubectl get nodes
      
      - name: Extract remediation details from PR
        id: remediation-details
        run: |
          PR_BODY='${{ github.event.pull_request.body }}'
          
          # Extract namespace and target name from PR body
          NAMESPACE=$(echo "$PR_BODY" | grep -oP 'Target: \K[^/]+' || echo "default")
          TARGET=$(echo "$PR_BODY" | grep -oP 'Target: [^/]+/\K[^ ]+' || echo "unknown")
          
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          
          echo "Applying remediation for $TARGET in namespace $NAMESPACE"
      
      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed YAML files
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.ya?ml$' || echo "")
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Apply Kubernetes manifests
        run: |
          CHANGED_FILES='${{ steps.changed-files.outputs.files }}'
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No YAML files changed, skipping apply"
            exit 0
          fi
          
          echo "Applying changed manifests:"
          echo "$CHANGED_FILES"
          
          # Apply each changed file
          echo "$CHANGED_FILES" | while read -r file; do
            if [ -n "$file" ]; then
              echo "Applying $file..."
              kubectl apply -f "$file"
            fi
          done
      
      - name: Verify deployment
        run: |
          NAMESPACE="${{ steps.remediation-details.outputs.namespace }}"
          TARGET="${{ steps.remediation-details.outputs.target }}"
          
          echo "Waiting for deployment rollout..."
          kubectl rollout status deployment/"$TARGET" -n "$NAMESPACE" --timeout=5m || true
          
          echo "Current deployment status:"
          kubectl get deployment "$TARGET" -n "$NAMESPACE"
      
      - name: Update Remediation CR status
        if: success()
        run: |
          # Extract PR number
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          # Find corresponding Remediation CR
          REMEDIATIONS=$(kubectl get remediations -A -o json | \
            jq -r --arg pr "$PR_NUMBER" '.items[] | select(.status.prNumber == ($pr | tonumber)) | "\(.metadata.namespace)/\(.metadata.name)"')
          
          if [ -n "$REMEDIATIONS" ]; then
            echo "Updating Remediation CR status..."
            for REM in $REMEDIATIONS; do
              NAMESPACE=$(echo "$REM" | cut -d'/' -f1)
              NAME=$(echo "$REM" | cut -d'/' -f2)
              
              kubectl patch remediation "$NAME" -n "$NAMESPACE" --type=merge -p '{
                "status": {
                  "phase": "Succeeded",
                  "reason": "Applied via GitHub Actions",
                  "appliedAt": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
                }
              }'
            done
          else
            echo "No matching Remediation CR found for PR #$PR_NUMBER"
          fi
      
      - name: Comment on PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '✅ Remediation applied successfully to cluster via GitHub Actions!'
            });
      
      - name: Handle failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '❌ Failed to apply remediation. Check the Actions log for details.'
            });
